# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aes.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_hashSum(object):
    def setupUi(self, hashSum):
        hashSum.setObjectName("hashSum")
        hashSum.resize(800, 600)
        self.label = QtWidgets.QLabel(hashSum)
        self.label.setGeometry(QtCore.QRect(20, 30, 621, 91))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.file_dir = QtWidgets.QLineEdit(hashSum)
        self.file_dir.setGeometry(QtCore.QRect(10, 150, 511, 51))
        self.file_dir.setObjectName("file_dir")
        self.selectFile = QtWidgets.QPushButton(hashSum)
        self.selectFile.setGeometry(QtCore.QRect(550, 150, 161, 51))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(20)
        self.selectFile.setFont(font)
        self.selectFile.setObjectName("selectFile")
        self.encode = QtWidgets.QPushButton(hashSum)
        self.encode.setGeometry(QtCore.QRect(160, 480, 161, 61))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(20)
        self.encode.setFont(font)
        self.encode.setObjectName("encode")
        self.key = QtWidgets.QLineEdit(hashSum)
        self.key.setGeometry(QtCore.QRect(10, 370, 511, 51))
        self.key.setObjectName("key")
        self.label_2 = QtWidgets.QLabel(hashSum)
        self.label_2.setGeometry(QtCore.QRect(20, 250, 251, 101))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.decode = QtWidgets.QPushButton(hashSum)
        self.decode.setGeometry(QtCore.QRect(470, 480, 161, 61))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(20)
        self.decode.setFont(font)
        self.decode.setObjectName("decode")

        self.retranslateUi(hashSum)
        QtCore.QMetaObject.connectSlotsByName(hashSum)

    def retranslateUi(self, hashSum):
        _translate = QtCore.QCoreApplication.translate
        hashSum.setWindowTitle(_translate("hashSum", "AES加解密"))
        self.label.setText(_translate("hashSum", "选择文件或直接输入要加密的文本"))
        self.selectFile.setText(_translate("hashSum", "打开"))
        self.encode.setText(_translate("hashSum", "加密"))
        self.label_2.setText(_translate("hashSum", "输入口令"))
        self.decode.setText(_translate("hashSum", "解密"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    hashSum = QtWidgets.QWidget()
    ui = Ui_hashSum()
    ui.setupUi(hashSum)
    hashSum.show()
    sys.exit(app.exec_())
